### ISSUE TITLE
LICENSE files missing.

### ISSUE THREAD

**Issue by MistressPlague** [PingerSurprise/VrcLovenseConnect#1]
LICENSE files missing for used libraries. They need included to be in accordance with the licensing.

Note they also need included in any even partial copies of the software, such as releases, source code and alike.

**Comment by PingerSurprise** [comment]
Thank you for adding the files, and my apologies for this oversight.

**Comment by MistressPlague** [comment]
License was deleted in last commit; it needs to be included to comply with the license.

**Comment by PingerSurprise** [comment]
License was merged with root LICENSE file.
New LICENSE file for LovenseConnectCSharp added back next to its source for better compliance.
