### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by nhede** [PingerSurprise/VrcLovenseConnect#4]
High CPU usage on no osc messages.
Please add sleep in OscModule.cs like:
`
if (messageReceived)
{ /*somecode*/
}
else
{
Thread.Sleep(100);
 }
`

**Comment by PingerSurprise** [comment]
Suggested solution has been implemented, reduced CPU usage to 0% when no OSC message is received
Time of wait will be proportional to the "limit" setting in the config.json file.
Thank you for your input.
