### ISSUE TITLE
Lovense connect address issue

### ISSUE THREAD

**Issue by nhede** [PingerSurprise/VrcLovenseConnect#5]
(this issue post is more for information to others who have connection problems)

Was not able to connect to my phone with the displayed link:
https://192-168-2-19.lovense.club:30010/GetToys
But it did work when changed to:
http://192.168.2.19:20010/GetToys

**Comment by PingerSurprise** [comment]
The port is different between the two provided links. Have you tested with the following address?
https://192-168-2-19.lovense.club:20010/GetToys

**Comment by nhede** [comment]
yes, I tried but doesn't work for me. I tried:
https://192-168-2-19.lovense.club:30010/GetToys
https://192-168-2-19.lovense.club:20010/GetToys
http://192-168-2-19.lovense.club:20010/GetToys
http://192-168-2-19.lovense.club:30010/GetToys
https://192.168.2.19:30010/GetToys

only, http://192.168.2.19:20010/GetToys works for me.

ping lovense.club gets me 44.230.252.214
ping 192-168-2-19.lovense.club gets me "could not find host"
this is why I switched over to use ip directly

this is the string I got from https://api.lovense.com/api/lan/getToys
and you can see the portnumbers in there too

`{"192-168-2-19.lovense.club":{"deviceId":"connect_bc6f88f50aaf47e9a2c687ffd656e492","domain":"192-168-2-19.lovense.club","httpPort":20010,"wsPort":20010,"httpsPort":30010,"wssPort":30010,"toyJson":"{\"df0548ccf4a9\":{\"nickName\":\"\",\"hVersion\":\"2\",\"fVersion\":204,\"name\":\"edge\",\"id\":\"df0548ccf4a9\",\"battery\":100,\"version\":\"2\",\"status\":1}}","platform":"android","appVersion":"2.8.1","appType":"connect","deviceCode":"5bd543","toys":{"df0548ccf4a9":{"nickName":"","hVersion":"2","fVersion":204,"name":"edge","id":"df0548ccf4a9","battery":100,"version":"2","status":1}}}}`

**Comment by PingerSurprise** [comment]
I will add a notice in the program's front page. Thank you for your input.
