### ISSUE TITLE
Archive; no longer works as of EAC VRC update coming soon.

### ISSUE THREAD

**Issue by MistressPlague** [PingerSurprise/VrcLovenseConnect#7]
Due to the EAC VRC update coming very soon this will be useless. Only RealFeel will work after it; which I personally don't see as an issue.

**Comment by PingerSurprise** [comment]
Hi,

VRCLovenseConnect does not require client mods to work with VRChat. It's a standalone program that listens to OSC messages and sends proximity contact values to either a LovenseConnect or Buttplug.io toy.

So it complies with VRC's terms and will be usable with EAC, as long as it's use in private instances of course.
