### ISSUE TITLE
i cant make it run on linux

### ISSUE THREAD

**Issue by Teru-dot-png** [PingerSurprise/VrcLovenseConnect#9]
any idea why i been having a fair share of problems
![image](https://user-images.githubusercontent.com/68662335/192951212-7fcb75c9-a80c-446c-821b-837b7119a658.png)

**Comment by PingerSurprise** [comment]
VRCLovenceConnect is built for Windows 64-bit systems. It hasn't been built for Linux systems since VRChat isn't officially supported on Linux.

**Comment by Teru-dot-png** [comment]
![image](https://user-images.githubusercontent.com/68662335/193240069-97a1f5a1-571a-4f8e-b451-fb31ad0b5be9.png)
![image](https://user-images.githubusercontent.com/68662335/193240131-efedc3ee-057f-4f5b-8b53-45ecc7b3c22b.png)
![image](https://user-images.githubusercontent.com/68662335/193240152-7dc1c606-4b56-4d6a-ae54-77965cbb7cbf.png)
the quickest solve of my life 
thanks for the good software <3

**Comment by PingerSurprise** [comment]
You're welcome! Glad you found a workaround. I'll archive this thread in case someone else needs it.
